on:
  push:
    branches:
      - master
name: 🚀 Deploy website on webwizard.in
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: DEPLOY CODE TO VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          port: ${{ secrets.PORT }}
          source: ./dist
          target: /var/www/webwizard.in

      - name: Run the application
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST_NAME}}
          username: ${{secrets.USER_NAME}}
          password: ${{secrets.PASS_WORD}}
          port: ${{secrets.PORT}}
          script: |
            cd /var/www/html
            cp -a dist/. ./
            rm -rf dist
