on:
  push:
    branches:
      - master
name: 🚀 Deploy to webwizard.in
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: DEPLOY CODE TO VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASS_WORD }}
          port: ${{ secrets.PORT }}
          script: |
            rsync -r --quiet $GITHUB_WORKSPACE/dist/ /var/www/webwizard.in
