on:
  push:
    branches:
      - master
name: 🚀 Deploy to webwizard.in
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: DEPLOY CODE TO VPS
        run: rsync -r --quiet -e "sshpass -p ${{ secrets.PASS_WORD }} ssh" $GITHUB_WORKSPACE/dist/ ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }}:/var/www/webwizard.in
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          PASS_WORD: ${{ secrets.PASS_WORD }}
